-- 코드를 작성해주세요
SELECT 
    COUNT(*) AS FISH_COUNT,
    (SELECT FISH_NAME 
     FROM FISH_NAME_INFO 
     WHERE FISH_TYPE = F.FISH_TYPE) AS FISH_NAME
FROM FISH_INFO F
GROUP BY F.FISH_TYPE
ORDER BY FISH_COUNT DESC