-- 코드를 작성해주세요
WITH AVG_S AS (
    SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
), EMP_G AS (
    SELECT EMP_NO, 
    CASE
        WHEN AVG_SCORE >= 96 THEN 'S'
        WHEN AVG_SCORE >= 90 THEN 'A'
        WHEN AVG_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END
    AS GRADE
    FROM AVG_S
)


SELECT E.EMP_NO, EMP_NAME, GRADE, 
    CASE
        WHEN GRADE = 'S' THEN SAL*0.2
        WHEN GRADE = 'A' THEN SAL*0.15
        WHEN GRADE = 'B' THEN SAL*0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES E
JOIN EMP_G
ON E.EMP_NO = EMP_G.EMP_NO