-- 코드를 입력하세요

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE>='2022-08-01' AND START_DATE<='2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*)>=5
) AND START_DATE>='2022-08-01' AND START_DATE<='2022-10-31'
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE), CAR_ID DESC




/*
start_date enddate가 2022-08사이
car_id별로 묶기
count(*)가 >=5 이상인 car_id_list

그룹화: 월, car_id
정렬:  월 오름차순, car_id 내림차순

*/