-- 코드를 작성해주세요

# 물고기 종류별 가장 큰 물고기의 길이
SELECT F.ID, FISH_NAME, F.LENGTH
FROM FISH_INFO F
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) ML
ON F.FISH_TYPE = ML.FISH_TYPE AND F.LENGTH=ML.LENGTH
JOIN FISH_NAME_INFO N
ON  ML.FISH_TYPE=N.FISH_TYPE
ORDER BY F.ID;